# Generated by Django 4.2.5 on 2023-10-09 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAPP', '0002_disco_periferico'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('procesador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaAPP.procesador')),
            ],
        ),
    ]
