# Generated by Django 4.2.5 on 2023-10-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAPP', '0004_usuario_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
