# Generated by Django 4.2.5 on 2023-10-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAPP', '0006_remove_customuser_direccion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
