# Generated by Django 4.2.5 on 2023-10-14 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TiendaAPP', '0006_delete_carritoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discos', models.ManyToManyField(blank=True, to='TiendaAPP.disco')),
                ('fuentes', models.ManyToManyField(blank=True, to='TiendaAPP.fuente')),
                ('memorias', models.ManyToManyField(blank=True, to='TiendaAPP.memoria')),
                ('motherboards', models.ManyToManyField(blank=True, to='TiendaAPP.motherboard')),
                ('perifericos', models.ManyToManyField(blank=True, to='TiendaAPP.periferico')),
                ('procesadores', models.ManyToManyField(blank=True, to='TiendaAPP.procesador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
