# Generated by Django 4.2.5 on 2023-10-14 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAPP', '0008_carritoitem_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoDisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('Disco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaAPP.disco')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoFuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('Fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaAPP.fuente')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoMemoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('Memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaAPP.memoria')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoMotherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('Motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaAPP.motherboard')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoPeriferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('Periferico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaAPP.periferico')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoProcesador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('procesador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaAPP.procesador')),
            ],
        ),
        migrations.DeleteModel(
            name='CarritoItem',
        ),
    ]
