# Generated by Django 4.2.5 on 2023-10-14 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TiendaAPP', '0009_carritodisco_carritofuente_carritomemoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disco', models.ManyToManyField(blank=True, to='TiendaAPP.disco')),
                ('Fuente', models.ManyToManyField(blank=True, to='TiendaAPP.fuente')),
                ('Memoria', models.ManyToManyField(blank=True, to='TiendaAPP.memoria')),
                ('Motherboard', models.ManyToManyField(blank=True, to='TiendaAPP.motherboard')),
                ('Perifericos', models.ManyToManyField(blank=True, to='TiendaAPP.periferico')),
                ('Procesador', models.ManyToManyField(blank=True, to='TiendaAPP.procesador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='carritofuente',
            name='Fuente',
        ),
        migrations.RemoveField(
            model_name='carritomemoria',
            name='Memoria',
        ),
        migrations.RemoveField(
            model_name='carritomotherboard',
            name='Motherboard',
        ),
        migrations.RemoveField(
            model_name='carritoperiferico',
            name='Periferico',
        ),
        migrations.RemoveField(
            model_name='carritoprocesador',
            name='procesador',
        ),
        migrations.DeleteModel(
            name='CarritoDisco',
        ),
        migrations.DeleteModel(
            name='CarritoFuente',
        ),
        migrations.DeleteModel(
            name='CarritoMemoria',
        ),
        migrations.DeleteModel(
            name='CarritoMotherboard',
        ),
        migrations.DeleteModel(
            name='CarritoPeriferico',
        ),
        migrations.DeleteModel(
            name='CarritoProcesador',
        ),
    ]
