# Generated by Django 4.2.5 on 2023-10-14 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAPP', '0010_carrito_remove_carritofuente_fuente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='Disco',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='Fuente',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='Memoria',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='Motherboard',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='Perifericos',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='Procesador',
        ),
        migrations.AddField(
            model_name='carrito',
            name='cantidad_disco',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrito',
            name='cantidad_fuente',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrito',
            name='cantidad_memoria',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrito',
            name='cantidad_motherboard',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrito',
            name='cantidad_periferico',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrito',
            name='cantidad_procesador',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrito',
            name='periferico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TiendaAPP.periferico'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='disco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TiendaAPP.disco'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='fuente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TiendaAPP.fuente'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='memoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TiendaAPP.memoria'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='motherboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TiendaAPP.motherboard'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='procesador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TiendaAPP.procesador'),
        ),
    ]
