# Generated by Django 4.2.5 on 2023-10-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAPP', '0010_remove_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_de_usuario',
            field=models.CharField(default='0', max_length=50, unique=True),
        ),
    ]
