# Generated by Django 4.2.5 on 2023-10-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAPP', '0011_remove_carrito_disco_remove_carrito_fuente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='cantidad_disco',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='cantidad_fuente',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='cantidad_memoria',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='cantidad_motherboard',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='cantidad_periferico',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='cantidad_procesador',
        ),
    ]
