# Generated by Django 4.2.5 on 2023-10-14 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAPP', '0012_remove_carrito_cantidad_disco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoDeCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaAPP.carritodecompras')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Procesador', 'Procesador'), ('Memoria', 'Memoria'), ('Fuente', 'Fuente'), ('Motherboard', 'Motherboard'), ('Disco', 'Disco'), ('Periferico', 'Periferico')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaAPP.producto'),
        ),
        migrations.AddField(
            model_name='carritodecompras',
            name='productos',
            field=models.ManyToManyField(through='TiendaAPP.ItemCarrito', to='TiendaAPP.producto'),
        ),
    ]
