# Generated by Django 4.2.5 on 2023-10-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAPP', '0014_carrito_remove_itemcarrito_carrito_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
